# Generated by Django 5.2.7 on 2025-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternative_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/alt/'),
        ),
    ]
