# Generated by Django 5.2.7 on 2025-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
